// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// composite //
// --------- //

#define composite_wrap_target 0
#define composite_wrap 3

static const uint16_t composite_program_instructions[] = {
            //     .wrap_target
    0xc000, //  0: irq    nowait 0                   
    0x6028, //  1: out    x, 8                       
    0xa001, //  2: mov    pins, x                    
    0x0041, //  3: jmp    x--, 1                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program composite_program = {
    .instructions = composite_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config composite_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + composite_wrap_target, offset + composite_wrap);
    return c;
}

//
// Initialise the PIO
// Parameters:
// - pio: The PIO to attach this to
// - sm: The state machine number
// - offset: The instruction memory offset the program is loaded at
// - pin_base: The number of the first GPIO pin to use in the PIO
// - pin_count: The number of consecutive GPIO pins to write to
// - freq: The frequency of the PIO state machine
//
// 
void composite_initialise_pio(PIO pio, uint sm, uint offset, uint pin_base, uint pin_count, double freq) {
    for(uint i=pin_base; i<pin_base+pin_count; i++) {
        pio_gpio_init(pio, i);
    }
    pio_sm_set_consecutive_pindirs(pio, sm, pin_base, pin_count, true);
    pio_sm_config c = composite_program_get_default_config(offset);
    sm_config_set_set_pins(&c, pin_base, pin_count);
    sm_config_set_out_pins(&c, pin_base, pin_count);
    sm_config_set_out_shift(&c, false, true, 8);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    pio_sm_init(pio, sm, offset, &c);
    pio->sm[sm].clkdiv = (uint32_t) (freq * (1 << 16));
}

#endif

